<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"><link rel="alternate" type="application/rss+xml" title="RSS" href="rss.xml"><link rel="shortcut icon" href="/media/img/effbot.ico"><link rel="stylesheet" href="/media/css/effbot-min.css" type="text/css" media="screen"><link rel="stylesheet" href="/media/css/effbotprint-min.css" type="text/css" media="print"><title>Errata for Python Imaging Library&nbsp;1.1.4</title></head><body data-page-id="184"><div id="doc2" class="yui-t2"><div id="hd"></div><div id="bd"><div id="yui-main"><div class="yui-b"><div class="content"><div class="yui-g"><h1 class="maintitle">Errata for Python Imaging Library&nbsp;1.1.4</h1></div><div class="yui-ge"><div class="yui-u first"><dl><dt><b>On this page:</b>
</dt><dt><a href="#pil172">Problems building the _imagingft extension</a>
</dt><dt><a href="#pil132">&#8220;NameError: global name &#8216;x&#8217; is not defined&#8221;</a>
</dt><dt><a href="#pil124">&#8220;NameError: name &#8216;EXTRA_COMPILE_ARGS&#8217; is not defined&#8221;</a>
</dt></dl><h2 id="pil172">Problems building the _imagingft extension (@PIL172)&#160;<a class="nav" href="#pil172" title="bookmark!">#</a></h2></div><div class="yui-u">&#160;</div></div><div class="yui-g"><p class="wide">PIL may not build cleanly with recent versions of the <b>freetype2</b> library (version 2.1 and later).  This usually results in a message similar
to this one:

<pre class="wide">
building '_imagingft' extension
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -O3 -Wall -Wstrict-prototypes
-fPIC -IlibImaging -I/usr/include/freetype2 -I/usr/local/include/python2.3
-c _imagingft.c -o build/temp.linux-i686-2.3/_imagingft.o
In file included from _imagingft.c:20:
/usr/include/freetype2/freetype/freetype.h:20:2:
  #error "`ft2build.h' hasn't been included yet!"
/usr/include/freetype2/freetype/freetype.h:21:2:
  #error "Please always use macros to include FreeType header files."
/usr/include/freetype2/freetype/freetype.h:22:2:
  #error "Example:"
/usr/include/freetype2/freetype/freetype.h:23:2:
  #error "  #include &lt;ft2build.h&gt;"
/usr/include/freetype2/freetype/freetype.h:24:2:
  #error "  #include FT_FREETYPE_H"
error: command 'gcc' failed with exit status 1
</pre></p></div><div class="yui-ge"><div class="yui-u first"><p>To work around this, you have to edit the <b>_imagingft.c</b> file.
Change the file as shown by this patch:</p><pre>
--- _imagingft.c
+++ _imagingft.c
@@ -17,7 +17,8 @@
 #include "Python.h"
 #include "Imaging.h"

-#include &lt;freetype/freetype.h&gt;
+#include &lt;ft2build.h&gt;
+#include FT_FREETYPE_H

 #if defined(PY_VERSION_HEX) &amp;&amp; PY_VERSION_HEX &lt; 0x01060000
 #define PyObject_DEL(op) PyMem_DEL((op))
</pre>

(this has been fixed in 1.1.5.  the new build process automatically
identifies freetype 2.0 and 2.1, and uses the correct include files
for the available version)

<h2 id="pil132">&#8220;NameError: global name &#8216;x&#8217; is not defined&#8221; (@PIL132)&#160;<a class="nav" href="#pil132" title="bookmark!">#</a></h2>

The OleFileIO module contains a typo that tends to reveal itself in
odd occasions (usually when trying to open something that looks like,
but isn&#8217;t, a FlashPix image).  Here&#8217;s a fix:

</div><div class="yui-u">&#160;</div></div><div class="yui-g"><pre class="wide wide">
Index: OleFileIO.py
===================================================================
--- OleFileIO.py        (revision 214)
+++ OleFileIO.py        (revision 261)
@@ -295,7 +296,7 @@
         fat = []
         for i in range(0, len(sect), 4):
             ix = i32(sect, i)
-            if ix == 0xFFFFFFFEL or x == 0xFFFFFFFFL:
+            if ix == 0xFFFFFFFEL or ix == 0xFFFFFFFFL:
                 break
             s = self.getsect(ix)
             fat = fat + map(lambda i, s=s: i32(s, i), range(0, len(s), 4))
</pre>

(this has been fixed in 1.1.5)

</div><div class="yui-ge"><div class="yui-u first"><h2 id="pil124">&#8220;NameError: name &#8216;EXTRA_COMPILE_ARGS&#8217; is not defined&#8221; (@PIL124)&#160;<a class="nav" href="#pil124" title="bookmark!">#</a></h2><p>Thanks to some last-minute OS X modifications to the <b>setup.py</b>
file, you may get NameError exceptions when building PIL.</p><pre>
Traceback (most recent call last):
  File "setup.py", line 287, in ?
    extra_compile_args=EXTRA_COMPILE_ARGS,
NameError: name 'EXTRA_COMPILE_ARGS' is not defined
</pre><p>If you get this error, the following patch should do the trick:</p><pre>
*** Imaging-1.1.4/setup.py Fri May  9 14:00:56 2003
--- Imaging-1.1.4-osx/setup.py Wed Jul 30 14:44:15 2003
***************
*** 216,222 ****
                  ["_imagingtk.c", "Tk/tkImaging.c"],
                  include_dirs=INCLUDE_DIRS,
                  library_dirs=LIBRARY_DIRS,
!                 libraries=LIBRARIES
                  )
              )

--- 216,224 ----
                  ["_imagingtk.c", "Tk/tkImaging.c"],
                  include_dirs=INCLUDE_DIRS,
                  library_dirs=LIBRARY_DIRS,
!                 libraries=LIBRARIES,
!                 extra_compile_args=EXTRA_COMPILE_ARGS,
!                 extra_link_args=EXTRA_LINK_ARGS
                  )
              )

***************
*** 284,291 ****
                  include_dirs=INCLUDE_DIRS,
                  library_dirs=LIBRARY_DIRS,
                  libraries=LIBRARIES,
-                 extra_compile_args=EXTRA_COMPILE_ARGS,
-                 extra_link_args=EXTRA_LINK_ARGS
                  )
              )

--- 286,291 ----
</pre>

(this is fixed in 1.1.5, of course.  no need to report it again.)</div><div class="yui-u">&#160;</div></div><div class="yui-g"></div></div></div></div><div class="yui-b"><div id='menu'><ul><li><b><a href="/" title="Go to effbot.org.">::: effbot.org</a></b></li><li><b><a href="." title="Go to zone index page.">::: zone :::</a></b></li></ul><ul><li><b>::: contents</b></li></ul><ul><li><ul><li><a href="#pil172">Problems building the _imagingft extension (@PIL172)</a></li><li><a href="#pil132">&#8220;NameError: global name &#8216;x&#8217; is not defined&#8221; (@PIL132)</a></li><li><a href="#pil124">&#8220;NameError: name &#8216;EXTRA_COMPILE_ARGS&#8217; is not defined&#8221; (@PIL124)</a></li></ul></li></ul></div></div></div><div id="ft"><p><a href="http://www.djangoproject.com/"><img src="/media/img/djangosite80x15.gif" border="0" alt="A Django site." title="A Django site." style="vertical-align: bottom;" width="80" height="15" ></a>
rendered by a <a href="http://www.djangoproject.com/">django</a> application.  hosted by <a href="http://www.webfaction.com/shared_hosting?affiliate=slab">webfaction</a>.</p></div></div><script src="/media/js/effbot-min.js" type="text/javascript"></script></body></html>
